# Generated by Django 4.0.2 on 2022-05-27 19:40

from django.db import migrations, models
import foodle.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodle', '0003_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=foodle.models.upload_path),
        ),
    ]
